### ISSUE TITLE
The border is not correctly exported to Excel when the cells are merged, or when colSpan is used in a workbook.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2401]
### Bug report

The border is not correctly exported to Excel when the cells are merged, or when colSpan is used in a workbook.

### Reproduction of the problem

The issue can be reproduced in the following demos:

Workbook:

http://dojo.telerik.com/edame

Spreadsheet:

http://dojo.telerik.com/iVImay

### Environment

* **Browser:** [all]

**Comment by ipeshev** [comment]
@mishoo looks like size of border is not respected ? Do we support this feature , else the bug is fixed

**Comment by IvanDanchev** [comment]
The Spreadsheet still does not export the border correctly in both of the originally described scenarios (merged cells and when colSpan is set): [dojo](http://dojo.telerik.com/eluJE/2) example.  (versions 2016.3.1118 and 2017.1.118).

**Comment by mishoo** [comment]
Fixed again.
