### ISSUE TITLE
The drop-down widget, part of the HeaderTemplate is placed outside the MVC Grid Header th element, when the Grid has at least 2 locked columns.

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3008]
### Bug report
When initializing a drop-down widget as part of the HeaderTemplate of a Grid column, the drop-down is placed outside of the corresponding *th* element. This is the case with an MVC grid with at least 2 columns being locked (one of them is the one with HeaderTemplate). A sample configuration of the Grid columns is the following:

```` C#
.Name("grid")
.Columns(columns =>
{
    columns.Bound(p => p.OrderID)
        .Locked(true)
        .Width(210)
.HeaderTemplate(@<text>@(Html.Kendo().DropDownList().Name("OrderID").DataTextField("Text").DataValueField("Value").BindTo((System.Collections.IEnumerable)ViewData["Sensors"]))</text>);
    columns.Bound(p => p.Freight).Width(200) .Locked(true);
    columns.Bound(p => p.ShipName).Width(300);
    columns.Bound(p => p.ShipCity).Width(300);
})
.Pageable()

````

### Reproduction of the problem
The problem could be observed on [the following picture](https://admin.telerik.com/ClientsFiles/97abee1a-2f5e-4941-91fc-f93de991f1df_with-locking.PNG).

### Environment

Kendo UI version: 2018.3.911

**Comment by veselints** [comment]
Viable workaround for the above is to call Deferred() on the DropDownLista and then at the end of the view call:
```` C#
@Html.Kendo().DeferredScripts()
````

**Comment by zdravkov** [comment]
It seems fixed with the latest version.

**Comment by Dimitar-Goshev** [comment]
The issue is still reproducible. The problem is that the DropDownList is placed outside the **th** element, instead of being placed in the **anchor** element inside the **th**. Thus, the DropDownList may appear in the second column header, shifting all other headers' text to the right and not showing the text for the last one:
![image](https://user-images.githubusercontent.com/6614183/31125852-76afbd4c-a852-11e7-9de9-67c4e77eec1e.png)

If a Button is used instead, it will be placed inside the **anchor** element:
![image](https://user-images.githubusercontent.com/6614183/31126005-027c5240-a853-11e7-9e58-189186aaf4a2.png)

**Comment by gyankov** [comment]
Does not reproduce with 2021 R2:

![image](https://user-images.githubusercontent.com/16634965/120427396-82a1cb80-c37a-11eb-86cb-48eb86c0674a.png)
