### ISSUE TITLE
Unable to clear virtualized ComboBox value

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4254]
### Bug report
Regression since R1 2018 SP1 - 2018.1.221

### Reproduction of the problem
https://dojo.telerik.com/@zdravkov/iQOMaBut
Clear the value of the second Combobox

### Current behavior
value is NOT cleared 

### Expected/desired behavior
value is cleared

### Environment
* **Kendo UI version:** 2018.2.516
* **Browser:** [all]

**Comment by jivanova** [comment]
https://dojo.telerik.com/avetUcOk Fixed with fixes in master

**Comment by nelito987** [comment]
The issue can be reproduced in Kendo UI for jQuery [ComboBox virtualization demo](https://demos.telerik.com/kendo-ui/combobox/virtualization) by adding filter "contains" . [Dojo example](https://dojo.telerik.com/@NeliKondova/AnInonOY)

**Comment by Dimitar-Goshev** [comment]
Another scenario, in which the issue is still reproducible - ComboBox from select element without filter:
- https://dojo.telerik.com/OdIliKEn
- Expand the first ComboBox
- Click on the clear button
Expected - value is cleared
Actual - _Suprêmes délices_ gets selected again. If the ComboBox is blurred, _Ottilies Käseladen_ is selected

NOTE: make sure to test it with/without filter and with/without expanded dropdown. And the options for clearing to be tested are: clear button, Backspace, Delete

**Comment by Dimitar-Goshev** [comment]
Another scenario (reproducible even before the latest fixes), in which the issue is still reproducible - **ComboBox from select element** without filter:

* https://dojo.telerik.com/OdIliKEn
* Select the text in the first ComboBox
* Press Backspace
* Blur the ComboBox
* Expand the ComboBox
* Expected - value is cleared
* Actual - Suprêmes délices gets selected again. If the ComboBox is blurred, Split Rail Beer & Ale is selected

NOTE: make sure to test it with/without filter and with/without expanded dropdown. And the options for clearing to be tested are: clear button, Backspace, Delete
