### ISSUE TITLE
Grouped Grid with editing and server operations does not fire dataSource change event on edit

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4503]
### Bug report

Grouped Grid with server operations does not fire dataSource change event on edit.

reported in 1340824 

### Reproduction of the problem

1. https://demos.telerik.com/aspnet-mvc/grid
1. enable editing & handle the change event of the dataSource 
1. group by column
1. edit an item

### Expected/desired behavior

The change event is fired.

### Environment

* **Kendo UI version:** 2018.3.911
* **Browser:** [all]

**Comment by matanasov** [comment]
@ag-petrov @gyankov 
After the fix the event is indeed fired but the editor is not closed when blurred with click **outside** of the grid

**Comment by gyankov** [comment]
@matanasov  The described behavior is caused due to the following issue: https://github.com/telerik/kendo/issues/9031

**Comment by matanasov** [comment]
Yes - it is resolved and should have been included in the R3 SP1 (2018.3.1017) release.

**Comment by kdgsmith** [comment]
Thank you Martin. I will give it a try.

**Comment by kdgsmith** [comment]
Hi Martin,

I just the above issue. i am still having the same issue. As soon as i add the grouping the datasource change event does not fire when changing a value in a cell.

**Comment by kdgsmith** [comment]
i fixed the issue it wasn't pulling the latest javascript through. Sorry. the event is being fired
