### ISSUE TITLE
Overlap in MultiSelect

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#748]
Observed in: Material, Material Black, Office 356, Fiori

![image](https://cloud.githubusercontent.com/assets/961037/7267798/5f723132-e8c9-11e4-9bde-171db0f66acf.png)

**Comment by dimodi** [comment]
Fixed by db3a941

**Comment by zacmackenzie** [comment]
I am still seeing this bug as an issue when using Fiori. How was this fixed?

**Comment by zacmackenzie** [comment]
I'm new to github and see the fix now. Thanks!
